Attempting to open file inputs/unrec2.fits
File opened successfully.
Running basic FITS verification with external call to ftverify.
Nothing from ftverify, trying with astropy.io.fits.verify(option='exception')
